# Generated by Django 4.0.1 on 2022-02-08 17:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bangla', 'Bangla'), ('English', 'English'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi'), ('Arabic', 'Arabic')], default='Bangla', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='tuition/images/default.jpg', upload_to='tuition/images'),
        ),
    ]
